### ISSUE TITLE
Attribution of source would be nice

### ISSUE THREAD

**Issue by pixelspark** [Ben1152000/lumina#1]
Lots of stuff in this repo seems inspired/copied from https://github.com/pixelspark/pwlp (which I am fine with from a technical perspective! very nice to see a Python implementation).

For the copied bits (most of the .bin files as far as I can see), attribution of the original code is required. The [license for pwlp (MIT)](https://github.com/pixelspark/pwlp/blob/master/LICENSE.txt) says:

````
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
````

For the bits that are inspired by the original code (e.g. the instruction set) it would also be nice (but not legally required) to attribute to my original work.

**Comment by Ben1152000** [comment]
I just removed all of the binaries I copied from your repo. I was originally using them to test out the vm, but since I modified the way some of the instructions behave they're no longer of much use. I also added attribution for the ISA, since it was heavily inspired by your blog post. Hope that resolves your issue!
